accounts/urls.py
from django.conf.urls import patterns, url

from accounts.views import settings, add_device

urlpatterns = patterns('',
    url(r'^login/$', 'django.contrib.auth.views.login', { 'template_name': 'accounts/login.html' }, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', { 'next_page': '/accounts/login' }, name='logout'),
    
    url(r'^$', settings, name='settings'),
    url(r'^add_device/$', add_device, name='add_device'),
)

admin/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView

urlpatterns = patterns('',
	url(r'^$', RedirectView.as_view(url='/clients/')),

	url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^clients/', include('clients.urls', namespace='clients')),
    url(r'^stock/', include('stock.urls', namespace='stock')),
    
    url(r'^unifi/', include('unifi_control.urls', namespace='unifi')),
    
    url(r'^statistics/', include('statistics.urls', namespace='statistics')),
)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Admin devices		
class AdminDevice(models.Model):
	class Meta:
		db_table = 'admin_device'
	
	mac_address = models.CharField(max_length = 255)
	description = models.CharField(max_length = 255)
	
	user = models.ForeignKey(User, related_name='devices')

accounts/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from accounts.models import AdminDevice

@login_required
def settings(request):
	return render(request, 'accounts/settings.html', {
        'devices': request.user.devices
    })
    
@login_required
def add_device(request):
	data = { key: request.POST[key] for key in request.POST if key != 'csrfmiddlewaretoken' }
	
	device = AdminDevice(user=request.user, **data)
	device.mac_address = device.mac_address.upper()
	
	device.save()
	
	return HttpResponseRedirect(reverse('accounts:settings'))

accounts/templates/accounts/login.html
<html>
<head>
	<meta name="viewport" content="user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-title" content="Social Hotspot">
    <meta name="apple-mobile-web-app-capable" content="yes">
	
	<link rel="stylesheet" type="text/css" href="/static/semantic.min.css">
	
	<script type="text/javascript" src="/static/jquery-2.1.3.min.js"></script>
	<script src="/static/semantic.min.js"></script>
	
	<style>
		.content {
			margin-top: 50px;
		}
		
		.card h1 {
			margin-top: 0px;
		}
		
		form {
			margin-bottom: 0px;
		}
	</style>
</head>
<body>
	
	<div class="content">
		<div class="ui one column stackable center aligned page grid">
		   <div class="ui five wide column card">
		   	
		   		<div class="content">
			   		<h1 class="ui header">Social Hotspot</h1>
			   		
			   		<div class="meta">
				   		{% if form.errors %}
							<p>Your username and password didn't match. Please try again.</p>
						
						{% else %}
							<p>Login to continue to the dashboard</p>
					    {% endif %}
				   	</div>
				   	
				   	<div class="ui divider"></div>
			   		
			   		<div class="ui description form">
				        <form method="post" action="{% url 'accounts:login' %}">
							{% csrf_token %}
							
							<div class="field">
							    <div class="ui corner input">
								    <input type="text" name="username" placeholder="Username" />
							    </div>
							</div>
						    
						    <div class="field">
							    <div class="ui corner input">
								    <input type="password" name="password" placeholder="Password" />
							    </div>
						    </div>
							
							<input type="submit" value="Login &rsaquo;" class="ui primary button" />
							
							<input type="hidden" name="next" value="/" />
						</form>
			   		</div>
		   		</div>
		       
		   </div>
		</div>
	</div>

</body>
</html>

accounts/templates/accounts/settings.html
{% extends 'base.html' %}

{% block title %}Account settings{% endblock %}
{% block header %}Account settings &mdash; {{ request.user.first_name }} {{ request.user.last_name }}{% endblock %}

{% block sidebar %}
	{% include 'sidebar.html' with active_item='account' %}
{% endblock %}

{% block content %}
	<div class="ui-grid-a">
		<div class="ui-block-a" style="padding-right: 10px;">
			<ul data-role="listview" data-inset="true">
				<li data-role="list-divider">Admin devices</li>
		
				{% for device in devices.all %}
					<li>{{ device.mac_address}} &mdash; {{ device.description }}
				{% empty %}
					<li>You have no registered devices.</li>
				{% endfor %}
				
			</ul>
		</div>
			
		<div class="ui-block-b" style="padding-left: 10px;">
			<div data-role="listview" data-inset="true">
				<li data-role="list-divider">Add an admin device</li>
				
				<li>
					<form method="post" action="{% url 'accounts:add_device' %}">
						{% csrf_token %}
						
						Device name: <input type="text" name="description" />
						MAC address: <input type="text" name="mac_address" />
						
						<button data-theme="b" data-icon="plus">Add</button>
					</form>
				</li>
			</div>
		</div>
	</div>
{% endblock %}