admin/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView

urlpatterns = patterns('',
	url(r'^$', RedirectView.as_view(url='/clients/')),

	url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^clients/', include('clients.urls', namespace='clients')),
    url(r'^stock/', include('stock.urls', namespace='stock')),
    
    url(r'^unifi/', include('unifi_control.urls', namespace='unifi')),
    
    url(r'^statistics/', include('statistics.urls', namespace='statistics')),
)

stock/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required

from stock.views import overview, add

urlpatterns = patterns('',
    url(r'^$', overview, name='overview'),
    
    url(r'^add/$', add, name='add')
)

stock/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.core.urlresolvers import reverse

from django.contrib.auth.decorators import login_required

from clients.models import Hotspot
from unifi_control.models import UnifiController

from urllib2 import HTTPError
from django.contrib import messages
        
@login_required
def overview(request):
	
	controllers = UnifiController.get_with_stock()
	
	aps = []
	
	for controller in controllers:
		try:
			c = controller.controller()
			aps += c.get_aps()
			
		except HTTPError, e:
			messages.error(request, "The login credentials for controller '"+ controller.name +"' are incorrect.")
	
	aps = Hotspot.filter_used(aps)
	
	return render(request, 'stock/overview.html', {
	    'aps': aps
	})
    
@login_required   
def add(request):
	data = { key: request.POST[key] for key in request.POST if key != 'csrfmiddlewaretoken' }
	
	hotspot = Hotspot(**data)
	hotspot.save()
	
	return HttpResponseRedirect(reverse('stock:overview'))

stock/templates/stock/overview.html
{% extends 'base.html' %}

{% block title %}Stock overview{% endblock %}
{% block header %}Stock overview{% endblock %}

{% block sidebar %}
	{% include 'sidebar.html' with active_item='stock' %}
{% endblock %}

{% block content %}
	<div class="ui-grid-a">
		<div class="ui-block-a" style="padding-right: 10px;">

			<div data-role="listview" data-inset="true">
				<li data-role="list-divider">Stock hotspots</li>
				
				<li>
					{% if messages %}
						{% for message in messages %}		
							<div class="error">{{ message }}</div>
						{% endfor %}
					{% endif %}
					
					<ul data-role="listview" data-inset="true" data-filter="true">
				
						{% for ap in aps %}
							<li>
								<div class="ui-grid-c">
									<div class="ui-block-a">
										{{ ap.mac | upper }}
									</div>
									
									<div class="ui-block-b">
										{% if ap.model.upper == 'P2N' %}
											Picostation M2
										{% else %}
											Unifi AP
										{% endif %}
									</div>
									
									<div class="ui-block-c">
										<em>{{ ap.name }}</em>
									</div>
									
									<div class="ui-block-c">
										{% if ap.state %}
											<span class="connected">Connected</span>
										{% else %}
											<span class="disconnected">Disconnected</span>
										{% endif %}
									</div>
								</div>
							</li>
						{% empty %}
							<li>There are no hotspots available.</li>
						{% endfor %}
						
					</ul>
				</li>
			</div>
			
		</div>
			
		<div class="ui-block-b" style="padding-left: 10px; opacity: 0.5;">
			<div data-role="listview" data-inset="true">
				<li data-role="list-divider">Add hotspot to stock</li>
				
				<li>
					<form action="{% url 'stock:add' %}" method="post" name="add_form">
						{% csrf_token %}
						
						MAC address: <input type="text" name="mac_address" autofocus="true" />
						
						<button data-theme="b" data-icon="plus">Add</button>
					</form>
				</li>
			</div>
		</div>
	</div>
	
{% endblock %}