admin/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView

urlpatterns = patterns('',
	url(r'^$', RedirectView.as_view(url='/clients/')),

	url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^clients/', include('clients.urls', namespace='clients')),
    url(r'^stock/', include('stock.urls', namespace='stock')),
    
    url(r'^unifi/', include('unifi_control.urls', namespace='unifi')),
    
    url(r'^statistics/', include('statistics.urls', namespace='statistics')),
)

clients/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required

from clients.views import ClientList
from clients.views import ClientDetail
from clients.views import hotspots
from clients.views import add_hotspot
from clients.views import add_hotspots_ajax
from clients.views import set_unifi_site
from clients.views import portal
from clients.views import add
from clients.views import portal_preview
from clients.views import set_portal_settings

urlpatterns = patterns('',
    url(r'^$', login_required(ClientList.as_view()), name='overview'),
    
    url(r'^add/$', add, name='add'),
    
    url(r'^detail/(?P<slug>[\w-]+)/add-hotspots/$', add_hotspots_ajax, name='add-hotspots'),
    url(r'^detail/(?P<slug>[\w-]+)/set-unifi-site/$', set_unifi_site, name='set-unifi-site'),
    
    url(r'^detail/(?P<slug>[\w-]+)/$', login_required(ClientDetail.as_view()), name='detail'),
    
    url(r'^detail/(?P<slug>[\w-]+)/hotspots$', hotspots, name='hotspots'),
    url(r'^detail/(?P<slug>[\w-]+)/add_hotspot$', add_hotspot, name='add_hotspot'),
    
    url(r'^detail/(?P<slug>[\w-]+)/portal$', portal, name='portal'),
    url(r'^detail/(?P<slug>[\w-]+)/portal_settings$', set_portal_settings, name='set_portal_settings'),
    
    url(r'^portal/(?P<slug>[\w-]+)/$', portal_preview, name='portal_preview')
)

clients/models.py
from django.db import models
from django.db.models.signals import pre_save, post_save

from django.conf import settings

import requests

# Clients		
class Client(models.Model):
	class Meta:
		db_table = 'client'
	
	slug = models.SlugField(max_length = 50, blank = True)
	
	company_name = models.CharField(max_length = 255, null = True)
	contact_name = models.CharField(max_length = 255, null = True)
	
	email = models.EmailField(null = True)
	
	street = models.CharField(max_length = 100, null = True)
	number = models.IntegerField(null = True)
	city = models.CharField(max_length = 100, null = True)
	postal = models.CharField(max_length = 7, null = True)
	country = models.CharField(max_length = 2, null = True)
	
	unifi_site = models.CharField(max_length = 24, null = True)
	unifi_controller = models.ForeignKey('unifi_control.UnifiController', related_name='clients', null = True)
	
	parent = models.ForeignKey('Client', related_name='subclients', null = True)

# Portals	
class Portal(models.Model):
	class Meta:
		db_table = 'portal'
		
	client = models.OneToOneField(Client, related_name = 'portal')
	
	logo = models.ImageField(upload_to = 'logos', null = True)
	logo_margin = models.IntegerField(default = 0, null = False)
	
	background_color = models.CharField(max_length = 7, null = True)
	
	facebook_page_id = models.BigIntegerField(null = True)
	facebook_page_username = models.CharField(max_length = 255, null = True)
	
	def facebook_enabled(self):
		return (self.facebook_page_id is not None)
	
	email_enabled = models.BooleanField(default = False)
	checkin_enabled = models.BooleanField(default = False)
	direct_access = models.BooleanField(default = False)
	
	guest_password = models.CharField(max_length = 255, null = True)

	wpa_password = models.CharField(max_length = 64, null = True)
	
	def network_password_enabled(self):
		return (self.wpa_password is not None)
	
	base_template = models.CharField(max_length = 255, null = True)
	
	def password_enabled(self):
		return (self.guest_password and len(self.guest_password) != 0)
		
	def is_liked(self, graph):
		return (len(graph.get('me/likes/'+ str(self.facebook_page_id))['data']) > 0)
		
# Portal users
class PortalUser(models.Model):
	class Meta:
		db_table = 'portal_user'
		
	portal = models.ForeignKey('Portal', related_name='users', null = False)
	
	mac_address = models.CharField(max_length = 255, null = True)
	state = models.IntegerField(default = 0, null = False)
	
	ua = models.CharField(max_length = 255, null = True)
	ip = models.CharField(max_length = 255, null = True)
	
	landed = models.DateTimeField(auto_now_add = True)
	updated = models.DateTimeField(auto_now = True)
		
# Hotspots		
class Hotspot(models.Model):
	class Meta:
		db_table = 'hotspot'
	
	mac_address = models.CharField(max_length = 255, null = True)
	client = models.ForeignKey('Client', related_name='hotspots', null = True)
	
	external_id = models.IntegerField(null = False, default = 1000)
	
	def get_external_info(self):
		response = requests.get(settings.CILIS_API +'/hotspot/?id='+ str(self.external_id))
		response = response.json()
		
		return response
	
	@staticmethod
	def filter_used(aps):
		existing_macs = [ hotspot.mac_address for hotspot in Hotspot.objects.all() ]
		
		return [ ap for ap in aps if ap['mac'] not in existing_macs ]
	
	@staticmethod
	def latest_id():
		latest = Hotspot.objects.order_by('-external_id').first()
		
		if latest:
			return latest.external_id
		else:
			return 1000

# Automatically generate a client slug
def create_client_slug(sender, instance, **kwargs):
	if not instance.slug:
		from slugify import slugify
		
		instance.slug = slugify(instance.company_name)
	
# Automatically create client portal if client is new
def create_client_portal(sender, instance, created, **kwargs):
	if created:
	    portal = Portal(client = instance)
	    portal.save()
	
pre_save.connect(create_client_slug, sender = Client)
post_save.connect(create_client_portal, sender = Client)

clients/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.core.urlresolvers import reverse

from django.views.generic import ListView, DetailView

from clients.models import Client, Hotspot
from unifi_control.models import UnifiController

from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

from django.contrib import messages
from django.core import serializers

import re, json

class ClientList(ListView):
    model = Client
    context_object_name = 'clients'
    
    template_name = 'clients/overview.html'
 
class ClientDetail(DetailView):
    model = Client
    context_object_name = 'client'
    
    template_name = 'clients/detail.html'

@login_required
def hotspots(request, slug):
	client = Client.objects.get(slug = slug)
	
	if client.unifi_site:	
		hotspots = client.hotspots.all()
		
		return render(request, 'clients/hotspots.html', {
		    'client': client,
		    'hotspots': hotspots
		})
		
	else:
		# Setup is required
		if client.city:
			unifi_site_id = client.company_name +' '+ client.city
		else:
			unifi_site_id = client.company_name
		
		unifi_site_id = re.sub(r'[^A-Za-z0-9\-]', '', unifi_site_id.lower().replace(' ', ''))[:24]
		
		return render(request, 'clients/setup.html', {
		    'client': client,
		    'unifi_site_id': unifi_site_id
		})
	
@login_required
def portal(request, slug):
	client = Client.objects.get(slug = slug)
	
	if request.method == 'POST' and 'logo' in request.FILES:
		client.portal.logo = request.FILES['logo']
		client.portal.save()
	
	return render(request, 'clients/portal.html', {
	    'client': client,
	    'portal': client.portal,
	    
	    'preview_hotspot': client.hotspots.first()
	})
	
@login_required
def set_portal_settings(request, slug):
	client = Client.objects.get(slug = slug)
	portal = client.portal
	
	setting = request.POST['setting']
	value = request.POST['value']
	
	booleanFields = ['facebook_enabled', 'password_enabled', 'network_password_enabled']
	valueFields = ['facebook_page_id', 'guest_password', 'wpa_password', 'background_color', 'logo_margin']
	
	if not (setting in booleanFields):
		
		if setting in valueFields:
			if setting == 'wpa_password' and len(value) < 8:
				value = None
			elif setting == 'wpa_password' and len(value) >= 8:
				controller = client.unifi_controller.controller(client.unifi_site)
			
				controller.set_wpa_password(value)
					
			setattr(portal, setting, value)
		else:
			setattr(portal, setting, (value == 'true'))
			
	else:
		if setting == 'facebook_enabled' and value == 'false':
			portal.facebook_page_id = None
				
		elif setting == 'password_enabled' and value == 'false':
			portal.guest_password = None
			
		elif setting == 'network_password_enabled' and value == 'false':
			portal.wpa_password = None
			
			controller = client.unifi_controller.controller(client.unifi_site)
			controller.set_wpa_password(False)
	
	portal.save()
	
	return HttpResponse()
	
@login_required   
def add_hotspot(request, slug):
	client = Client.objects.get(slug = slug)
	
	hotspots = add_hotspots_from_stock(client, 1)
	
	if not hotspots:
		messages.error(request, 'There are no hotspots left in stock.')
	
	return HttpResponseRedirect(reverse('clients:hotspots', kwargs={ 'slug': client.slug }))

@csrf_exempt
def add_hotspots_ajax(request, slug):
	client = Client.objects.get(slug = slug)
	number_of_aps = int(request.POST.get('number_of_aps', 1))
	
	hotspots = add_hotspots_from_stock(client, number_of_aps)
	
	if hotspots:
		return HttpResponse(json.dumps({ 'hotspots': hotspots }), content_type='application/json')
	else:
		return HttpResponse(json.dumps({ 'error': "Not enough hotspots in stock" }), content_type='application/json')
	
def add_hotspots_from_stock(client, number_of_aps):
	controllers = UnifiController.get_with_stock()
	aps = []
	
	existing_macs = [ hotspot.mac_address for hotspot in Hotspot.objects.all() ]
	
	for c in controllers:
		c = c.controller()
		aps += c.get_aps()
	
	available = [ ap for ap in aps if ap['mac'] not in existing_macs ]

	if len(available) >= number_of_aps:
		hotspots = []
	
		for ap in range(0, number_of_aps):
			ap = available[ap]
		
			hotspot = Hotspot(mac_address = ap['mac'], client_id = client.id, external_id = (Hotspot.latest_id() + 1))
			hotspot.save()
			
			hotspots.append(hotspot)
			
		hotspots = [ { 'external_id': hotspot.external_id, 'mac_address': hotspot.mac_address } for hotspot in hotspots ]
			
		return hotspots
	else:
		return False
		
@csrf_exempt
def set_unifi_site(request, slug):
	client = Client.objects.get(slug = slug)
	
	site_id = request.POST['unifi_site_id']
	controller_id = request.POST['unifi_controller']

	client.unifi_site = site_id
	client.unifi_controller_id = controller_id
	
	client.save()
	
	return HttpResponse(True)

@login_required   
def add(request):
	data = { key: request.POST[key] for key in request.POST if key != 'csrfmiddlewaretoken' }
	
	client = Client(**data)
	client.save()
	
	return HttpResponseRedirect(reverse('clients:overview'))
	
@login_required
def portal_preview(request, slug):
	client = Client.objects.get(slug = slug)
	
	return render(request, 'clients/portal/cilis/start.html', {
	    'client': client
	})

clients/templates/clients/detail.html
{% extends 'base.html' %}

{% block header %}<span class="title-method">Editing client:</span> {{ client.company_name }}{% endblock %}

{% block sidebar %}
	{% include 'sidebar.html' with active_item='clients' %}
{% endblock %}

{% block tabs %}
	{% include 'clients/tabs.html' with active_item='info' %}
{% endblock %}

{% block content %}
	<div data-role="listview" data-inset="true">
		<li data-role="list-divider">Information</li>
		
		<li>
			<h1>{{ client.company_name }}</h1>
			<em>{{ client.contact_name }}</em>
		</li>
	</div>
{% endblock %}

clients/templates/clients/hotspots.html
{% extends 'clients/detail.html' %}

{% block tabs %}
	{% include 'clients/tabs.html' with active_item='hotspots' %}
{% endblock %}

{% block content %}

	<div data-role="listview" data-inset="true">
		<li data-role="list-divider">Hotspots</li>
		
		<li>
			{% if messages %}
				{% for message in messages %}		
					<div class="error">{{ message }}</div>
				{% endfor %}
			{% endif %}
			
			<ul data-role="listview" data-inset="true" data-filter="true">
		
				{% for hotspot in hotspots %}
					<li>
						<div class="ui-grid-a">
							<div class="ui-block-a">
								<em>#{{ hotspot.external_id }}</em>
							</div>
							
							<div class="ui-block-b">
								{{ hotspot.mac_address | upper }}
							</div>
						</div>
					</li>
				{% empty %}
					<li>There are no hotspots available.</li>
				{% endfor %}
				
			</ul>
			
			<div>
				<a href="add_hotspot" data-role="button" data-icon="plus" data-inline="true" data-mini="true">&nbsp;Attach new</a>
			</div>
		</li>
	</div>
{% endblock %}

clients/templates/clients/overview.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load sekizai_tags %}

{% block stylesheets %}
   <!-- DATATABLES-->
   <link rel="stylesheet" href="{% static 'theme/vendor/datatables-colvis/css/dataTables.colVis.css' %}">
   <link rel="stylesheet" href="{% static 'theme/vendor/datatable-bootstrap/css/dataTables.bootstrap.css' %}">
{% endblock %}

{% block title %}Client overview{% endblock %}
{% block header %}Client overview{% endblock %}

{% block sidebar %}
	{% include 'sidebar.html' with active_item='clients' %}
{% endblock %}

{% block content %}

	{% addtoblock 'js' %}
		<script src="{% static 'theme/vendor/datatables/media/js/jquery.dataTables.min.js' %}"></script>
		<script src="{% static 'theme/vendor/datatable-bootstrap/js/dataTables.bootstrap.js' %}"></script>
		<script src="{% static 'theme/vendor/datatable-bootstrap/js/dataTables.bootstrapPagination.js' %}"></script>
		
		<script src="{% static 'theme/js/datatable.js' %}"></script>
	{% endaddtoblock %}

	<div class="row">
		<div class="col-md-8">
			<div class="panel panel-default">
				<div class="panel-body">
					<legend>Clients</legend>
					
					<div class="table-responsive">
						<table class="table table-striped datatable">
							<thead>
							  <tr>
								 <th>#</th>
								 <th>Company name</th>
								 <th>Contact person</th>
							  </tr>
							</thead>
							<tbody>
								{% for client in clients %}
									<tr>
										<td>{{ client.pk }}</td>
										<td>
											<a href="{% url 'clients:detail' client.slug %}">
												{{ client.company_name }}
											</a>
										</td>
										<td>{{ client.contact_name }}</td>
									</tr>
								{% empty %}
									<td colspan="3">There are no clients available.</td>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
		
		<div class="col-md-4">
			<div class="panel panel-default">
				<div class="panel-body">
					<legend>Add new client</legend>
	                        
					<form role="form" method="post" action="{% url 'clients:add' %}">
						{% csrf_token %}
						
                        <div class="form-group">
							<label>Company name</label>
							<input type="text" name="company_name" placeholder="Café B.V." class="form-control">
						</div>
						
						<div class="form-group">
							<label>Contact person</label>
							<input type="text" name="contact_name" placeholder="J. Janssen" class="form-control">
						</div>
					
						<button type="submit" class="btn btn-labeled btn-info">
                           <span class="btn-label"><i class="fa fa-plus"></i>
                           </span>Add
                        </button>
					</form>
					
				</div>
			</div>
		</div>
	</div>
	
{% endblock %}

clients/templates/clients/portal.html
{% extends 'clients/detail.html' %}

{% block tabs %}
	{% include 'clients/tabs.html' with active_item='portal' %}
{% endblock %}

{% block content %}
	<div class="ui-grid-a">
		<div class="ui-block-a" style="padding-right: 10px;">
			<div data-role="listview" data-inset="true">
				<li data-role="list-divider">Logo</li>
				
				<li>
					<form method="post" enctype="multipart/form-data">
						{% csrf_token %}
						
						<input type="file" name="logo" id="logo" />
						<input type="submit" data-role="button" value="Upload logo" />
					</form>
					
					{% if portal.logo %}
						<hr />
						
						<div>
							<img src="http://globalwifiservices.com/media/{{ portal.logo }}" style="height: 100px;" />
						</div>
					{% else %}
						<em>No logo uploaded yet.</em>
					{% endif %}
				</li>
				
				<li data-role="list-divider">Logo margin (pixels)</li>
				
				<li>
					<input type="text" class="setting-field" id="logo_margin" value="{{ portal.logo_margin }}" />
				</li>
				
				<li data-role="list-divider">Header background color</li>
				
				<li>
					<input type="text" class="setting-field" id="background_color" value="{{ portal.background_color|default:"#FFFFFF" }}" />
				</li>
			</div>
			
			<div data-role="listview" data-inset="true">
				<li data-role="list-divider">Login methods</li>
				
				<li>
				
					<label>
						<input type="checkbox" name="facebook_enabled" {% if portal.facebook_enabled %}checked="true"{% endif %}>Facebook (like)
					</label>
					
					<div id="facebook_page_container" {% if not portal.facebook_enabled %}style="display: none;"{% endif %}>
						<input type="text" class="setting-field" id="facebook_page_id" placeholder="123456789" {% if portal.facebook_enabled %}value="{{ portal.facebook_page_id }}"{% endif %} />
					</div>
					
					<hr />
					
					<label>
						<input type="checkbox" name="checkin_enabled" {% if portal.checkin_enabled %}checked="true"{% endif %}>Facebook (check-in)
					</label>
					
					<hr />
					
					<label>
						<input type="checkbox" name="email_enabled" {% if portal.email_enabled %}checked="true"{% endif %}>Email address
					</label>
					
					<hr />
					
					<label>
						<input type="checkbox" name="password_enabled" {% if portal.password_enabled %}checked="true"{% endif %}>Password
					</label>
						
					<div id="guest_password_container" {% if not portal.password_enabled %}style="display: none;"{% endif %}>
						<input type="text" class="setting-field" id="guest_password" placeholder="Guest password" {% if portal.password_enabled %}value="{{ portal.guest_password }}"{% endif %} />
					</div>
					
					<hr />
					
					<label>
						<input type="checkbox" name="direct_access" {% if portal.direct_access %}checked="true"{% endif %}>Direct
					</label>
					
					<hr />
					
					<label>
						<input type="checkbox" name="network_password_enabled" {% if portal.network_password_enabled %}checked="true"{% endif %}>Network password (WPA)
					</label>
					
					<div id="wpa_password_container" {% if not portal.network_password_enabled %}style="display: none;"{% endif %}>
						<input type="text" class="setting-field" id="wpa_password" placeholder="123456789" {% if portal.network_password_enabled %}value="{{ portal.wpa_password }}"{% endif %} />
						
						<em><small>The password needs to be between 8 and 64 characters.</small></em>
					</div>
				
					<script type="text/javascript">
						$(document).ready(function() {
							
							$('input[type="checkbox"]').change(function() {
								var self = $(this);
								
								$.post('{% url "clients:set_portal_settings" client.slug %}',
										{ setting: $(this).attr('name'), value: $(this).is(':checked') }, function() {
											
											if(self.attr('name') == 'facebook_enabled') {
												
												$('#facebook_page_container').toggle()
												
												$('#facebook_page_id').val('')
												$('#facebook_page_id').focus()
												
											} else if(self.attr('name') == 'password_enabled') {
												
												$('#guest_password_container').toggle()
												
												$('#guest_password').val('')
												$('#guest_password').focus()
												
											} else if(self.attr('name') == 'network_password_enabled') {
												
												$('#wpa_password_container').toggle()
												
												$('#wpa_password').val('')
												$('#wpa_password').focus()
												
											}
											
											if(!((self.attr('name') == 'facebook_enabled' || self.attr('name') == 'password_enabled' || self.attr('name') == 'network_password_enabled') && self.is(':checked'))) {
												
												var url = $('#preview-frame').attr('src');
												$('#preview-frame').attr('src', url);
												
											}
										});
								
							});
							
							var keyTimer;
							$('.setting-field').on('keyup', function() {
								clearTimeout(keyTimer)
								var self = $(this);
								
								keyTimer = setTimeout(function() {
									
									$.post('{% url "clients:set_portal_settings" client.slug %}',
											{ setting: self.attr('id'), value: self.val() }, function() {
												
												$('#preview-frame').attr('src', $('#preview-frame').attr('src'));
												
											});
											
								}, 500);
								
								// Validation
								if($(this).attr('id') == 'wpa_password' && $(this).val().length < 8) {
									$(this).css('color', '#cccccc');
								} else {
									$(this).css('color', 'black');
								}
							});
							
						});
					</script>
				
				</li>
			</div>
			
		</div>
		
		<div class="ui-block-b" style="padding-left: 10px;">
			<div data-role="listview" data-inset="true">
				<li data-role="list-divider">Preview</li>
				
				<li>
					<iframe id="preview-frame" src="http://globalwifiservices.com/guest/s/{{ client.unifi_site }}?ap={{ preview_hotspot.mac_address }}&id=A1:B2:C3:D4:E5:F6" frameborder="0" style="width: 100%; height: 500px; border: 1px solid #ccc;"></iframe>
				</li>
			</div>
			
			<a data-role="button" data-theme="b" data-external="true" target="_blank" href="http://globalwifiservices.com/guest/s/{{ client.unifi_site }}?ap={{ preview_hotspot.mac_address }}&id=A1:B2:C3:D4:E5:F6">Open portal preview</a>
		</div>
	</div>
{% endblock %}

clients/templates/clients/setup.html
{% extends 'clients/detail.html' %}

{% load staticfiles %}
{% load sekizai_tags %}

{% block tabs %}
	{% include 'clients/tabs.html' with active_item='hotspots' %}
{% endblock %}

{% block content %}

	{% addtoblock 'js' %}	
		<script>
			client_slug = "{{ client.slug }}";
		</script>
		
		<script src="{% static 'theme/js/setup.js' %}"></script>
	{% endaddtoblock %}

	<div class="steps-container">
		
		<div data-role="listview" data-inset="true">
			<li data-role="list-divider">Client setup</li>
			
			<li>
				<div class="step" id="intro">
					<p>
						Before using this client, a Unifi site needs to be setup and relevant settings need to be applied.
					</p>
					
					<button data-theme="a" data-icon="forward" class="submit-button" id="run-all">Run all</button>
				</div>
			</li>
		</div>
		
		<div class="step-divider">&darr;</div>
		
		<div data-role="listview" data-inset="true">
			<li data-role="list-divider">Create a Unifi site</li>
			
			<li>
				<div class="step" id="create-unifi-site" data-busy-text="Creating Unifi site..." data-done-text="Unifi site has been created" data-next-step="set-general-settings">
					
					<p>
						A new Unifi site for this specific client needs to be created. Change the site name and ID when neccessary.
					</p>
					
					<hr />
					
					<label>Site name:</label>
					
					{% if client.city %}
						<input type="text" name="unifi_site_name" id="unifi_site_name" value="{{ client.company_name }} {{ client.city }}" />
					{% else %}
						<input type="text" name="unifi_site_name" id="unifi_site_name" value="{{ client.company_name }}" />
					{% endif %}
					
					<label>Site ID:</label>
					<input type="text" name="unifi_site_id" id="unifi_site_id" value="{{ unifi_site_id }}" />
					
					<button data-theme="b" data-icon="plus" class="submit-button">Create Unifi site</button>
					
				</div>
			</li>
		</div>
		
		<div class="step-divider">&darr;</div>
		
		<div data-role="listview" data-inset="true" style="opacity: 0.60;">
			<li data-role="list-divider">Set general site settings</li>
			
			<li>
				<div class="step" id="set-general-settings" data-busy-text="Updating site settings..." data-done-text="Site settings have been updated" data-next-step="set-guest-portal-settings">
					<p>
						Access points need to be attached to the created site. These access points will be moved from the stock site.
					</p>
					
					<button data-theme="b" data-icon="gear" class="submit-button">Set site settings</button>
				</div>
			</li>
		</div>
		
		<div class="step-divider">&darr;</div>
		
		<div data-role="listview" data-inset="true" style="opacity: 0.60;">
			<li data-role="list-divider">Set guest portal settings</li>
			
			<li>
				<div class="step" id="set-guest-portal-settings" data-busy-text="Updating guest portal settings..." data-done-text="Guest portal settings have been updated" data-next-step="add-wireless-networks">
					<p>
						Access points need to be attached to the created site. These access points will be moved from the stock site.
					</p>
					
					<button data-theme="b" data-icon="gear" class="submit-button">Set guest portal settings</button>
				</div>
			</li>
		</div>
		
		<div class="step-divider">&darr;</div>
		
		<div data-role="listview" data-inset="true" style="opacity: 0.60;">
			<li data-role="list-divider">Add wireless networks</li>
			
			<li>
				<div class="step" id="add-wireless-networks" data-busy-text="Adding wireless networks..." data-done-text="Wireless networks have been added" data-next-step="attach-access-points">
					<p>
						Access points need to be attached to the created site. These access points will be moved from the stock site.
					</p>
					
					<hr />
					
					<label>SSID:</label>
					<input type="text" id="ssid" value="FREE WIFI {{ client.company_name }}" />
					
					<label>Private SSID:</label>
					<input type="text" id="ssid_private" value="SH {{ client.company_name }}" />
					
					<label>Private password:</label>
					<input type="text" id="password_private" value="12345678" />
					
					<button data-theme="b" data-icon="cloud" class="submit-button">Add wireless networks</button>
				</div>
			</li>
		</div>
		
		<div class="step-divider">&darr;</div>
		
		<div data-role="listview" data-inset="true" style="opacity: 0.60;">
			<li data-role="list-divider">Attach access points from stock</li>
			
			<li>
				<div class="step" id="attach-access-points" data-busy-text="Moving access points to site..." data-done-text="Access points have been attached">
					<p>
						Access points need to be attached to the created site. These access points will be moved from the stock site.
					</p>
					
					<hr />
					
					<label>Number of access points:</label>
					<input type="number" id="number_of_aps" value="1" />
					
					<button data-theme="b" data-icon="power" class="submit-button">Attach access points</button>
				</div>
			</li>
		</div>
				
		<div id="aps_container" style="display: none;">
			<hr />
			
			<div data-role="listview" data-inset="true" id="aps">
				
			</div>
		</div>
		
		<div id="finish" style="text-align: center; margin-top: 60px; margin-bottom: 75px; margin-left: 225px; opacity: 0.4; width: 225px;">
			<button data-theme="b" data-icon="check" style="font-size: 17pt; font-weight: normal;" data-inline="true">Finish setup &raquo;</button>

			<div>This will set the Unifi site ID.</div>
		</div>
		
	</div>
	
{% endblock %}

clients/templates/clients/tabs.html
<div data-role="navbar">
	<ul>
		<li><a href="./" {% if active_item == 'info' %}class="ui-btn-active"{% endif %}>Information</a></li>
		<li><a href="hotspots" {% if active_item == 'hotspots' %}class="ui-btn-active"{% endif %}>Hotspots</a></li>
		<li><a href="portal" {% if active_item == 'portal' %}class="ui-btn-active"{% endif %}>Portal</a></li>
	</ul>	
</div>