accounts/urls.py
from django.conf.urls import patterns, url

from accounts.views import settings, add_device

urlpatterns = patterns('',
    url(r'^login/$', 'django.contrib.auth.views.login', { 'template_name': 'accounts/login.html' }, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', { 'next_page': '/accounts/login' }, name='logout'),
    
    url(r'^$', settings, name='settings'),
    url(r'^add_device/$', add_device, name='add_device'),
)

admin/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView

urlpatterns = patterns('',
	url(r'^$', RedirectView.as_view(url='/clients/')),

	url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^clients/', include('clients.urls', namespace='clients')),
    url(r'^stock/', include('stock.urls', namespace='stock')),
    
    url(r'^unifi/', include('unifi_control.urls', namespace='unifi')),
    
    url(r'^statistics/', include('statistics.urls', namespace='statistics')),
)

statistics/urls.py
from django.conf.urls import patterns, include, url
from statistics.views import facebook

urlpatterns = patterns('',
    url(r'^facebook/$', facebook, name='facebook'),
)

stock/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required

from stock.views import overview, add

urlpatterns = patterns('',
    url(r'^$', overview, name='overview'),
    
    url(r'^add/$', add, name='add')
)

admin/templates/base-old.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load staticfiles %}
	
    <link rel="stylesheet" href="{% static 'jquery.mobile-1.4.5.min.css' %}" />
    
    <script type="text/javascript" src="{% static 'jquery-2.1.3.min.js' %}"></script>
    
    <script type="text/javascript">
	$(document).bind("mobileinit", function () {
	    $.mobile.ajaxEnabled = false;
	});
	    
	$.ajaxSetup({ 
	     beforeSend: function(xhr, settings) {
	         function getCookie(name) {
	             var cookieValue = null;
	             if (document.cookie && document.cookie != '') {
	                 var cookies = document.cookie.split(';');
	                 for (var i = 0; i < cookies.length; i++) {
	                     var cookie = jQuery.trim(cookies[i]);
	                     // Does this cookie string begin with the name we want?
	                 if (cookie.substring(0, name.length + 1) == (name + '=')) {
	                     cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
	                     break;
	                 }
	             }
	         }
	         return cookieValue;
	         }
	         if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
	             // Only send the token to relative URLs i.e. locally.
	             xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
	         }
	     } 
	});
	</script>
	
	<script type="text/javascript" src="{% static 'jquery.mobile-1.4.5.min.js' %}"></script>
    
    <style>
	    .title-method {
		    font-weight: normal;
	    }
	    
	    hr {
		    background-color: #ccc;
		    border: none;
		    height: 1px;
	    }
	    
	    .error {
		    display: block;
		    
		    box-sizing: border-box;

		    padding-top: 15px;
		    padding-bottom: 15px;
		    padding-left: 15px;
		    
		    margin-bottom: 16px;
		    
		    background-color: #efefef;
		    
		    border-radius: 6px;
		    border: 1px solid rgb(221, 221, 221);
		    
		    font-weight: bold;
	    }
	    
	    .connected {
		    color: #007700;
	    }
	    
	    .disconnected {
		    color: #bb0000;
	    }
	    
	    .submit-button {
		    margin-top: 15px;
	    }
	    
	    .steps-container {
		    width: 680px;
		    margin: 0 auto;
	    }
	    
	    .steps-container div[data-role="listview"] {
		    
	    }
	    
	    .steps-container .step-divider {
		    text-align: center;
		    font-size: 16pt;
		    
		    color: #9e9e9e;
	    }
	    
	    .ui-listview>li .step p {
		    font-size: 10pt;
		    
		    white-space: normal;
		    overflow: visible;
		    text-overflow: inherit;
	    }
	    
	    li .step label {
		    font-size: 10pt;
		    
		    margin-top: 5px;
	    }
	    
	    li .step hr {
		    margin-bottom: 15px;
	    }
	    
	    li .step .ui-input-text {
		    margin-bottom: 15px;
	    }
	    
	    @media only screen and (max-width : 780px) {
				
			.steps-container {
				width: 100%;
			}
		}
	</style>
    
    <title>{% block title %}Social Hotspot{% endblock %}</title>
</head>

<body>
	<div data-role="page" data-url="{{ request.get_full_path }}">
 
        <div data-role="header" data-theme="b">
	        <h1>{% block header %}{% endblock %}</h1>
	        
            {% block menu %}
            	{% include 'menu.html' %}
            {% endblock %}

			{% block tabs %}{% endblock %}
        </div>
 
        <div data-role="content">
            {% block content %}{% endblock %}
        </div>
 
    </div>
</body>
</html>

admin/templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load sekizai_tags %}

<head>
   <meta charset="utf-8">
   
   <meta name="viewport" content="user-scalable=no, width=device-width">
   <meta name="apple-mobile-web-app-title" content="Social Hotspot">
   <meta name="apple-mobile-web-app-capable" content="yes">
   <meta name="apple-mobile-web-app-status-bar-style" content="black">

   <title>{% block title %}Social Hotspot{% endblock %}</title>
   
   {% load staticfiles %}
   
   <!-- =============== VENDOR STYLES ===============-->
   <!-- FONT AWESOME-->
   <link rel="stylesheet" href="{% static 'theme/vendor/fontawesome/css/font-awesome.min.css' %}">
   <!-- SIMPLE LINE ICONS-->
   <link rel="stylesheet" href="{% static 'theme/vendor/simple-line-icons/css/simple-line-icons.css' %}">
   <!-- ANIMATE.CSS-->
   <link rel="stylesheet" href="{% static 'theme/vendor/animate.css/animate.min.css' %}">
   <!-- WHIRL (spinners)-->
   <link rel="stylesheet" href="{% static 'theme/vendor/whirl/dist/whirl.css' %}">
   <!-- =============== PAGE VENDOR STYLES ===============-->
   <!-- WEATHER ICONS-->
   <link rel="stylesheet" href="{% static 'theme/vendor/weather-icons/css/weather-icons.min.css' %}">
   
   {% block stylesheets %}{% endblock %}
   
   <!-- =============== BOOTSTRAP STYLES ===============-->
   <link rel="stylesheet" href="{% static 'theme/css/bootstrap.css' %}" id="bscss">
   <!-- =============== APP STYLES ===============-->
   <link rel="stylesheet" href="{% static 'theme/css/app.css' %}" id="maincss">
</head>

<body>
	<div class="wrapper">
		
      <!-- top navbar-->
      <header class="topnavbar-wrapper">
         <!-- START Top Navbar-->
         
         {% block navigation %}
         	{% include 'navigation.html' %}
         {% endblock %}
         
         <!-- END Top Navbar-->
      </header>
      
      <!-- sidebar-->
      <aside class="aside">
         <!-- START Sidebar (left)-->
         <div class="aside-inner">
            <nav data-sidebar-anyclick-close="" class="sidebar">
               <!-- START sidebar nav-->
                 
			    {% block sidebar %}
	            	{% include 'sidebar.html' %}
	            {% endblock %}
	            
               <!-- END sidebar nav-->
            </nav>
         </div>
         <!-- END Sidebar (left)-->
      </aside>
      
      <!-- Main section-->
      <section>
         <!-- Page content-->
         <div class="content-wrapper">
	        <h3>
		       {% block header %}{% endblock %}
		       
               <!--<small>Subtitle</small>-->
            </h3>
            
            {% block content %}{% endblock %}
            
         </div>
      </section>
      
      <!-- Page footer-->
      <footer>
         <span>&copy; 2015 - Social Hotspot</span>
      </footer>
   </div>
   
   <!-- =============== VENDOR SCRIPTS ===============-->
   <!-- MODERNIZR-->
   <script src="{% static 'theme/vendor/modernizr/modernizr.js' %}"></script>
   <!-- JQUERY-->
   <script src="{% static 'theme/vendor/jquery/dist/jquery.js' %}"></script>
   <!-- BOOTSTRAP-->
   <script src="{% static 'theme/vendor/bootstrap/dist/js/bootstrap.js' %}"></script>
   <!-- STORAGE API-->
   <script src="{% static 'theme/vendor/jQuery-Storage-API/jquery.storageapi.js' %}"></script>
   <!-- JQUERY EASING-->
   <script src="{% static 'theme/vendor/jquery.easing/js/jquery.easing.js' %}"></script>
   <!-- ANIMO-->
   <script src="{% static 'theme/vendor/animo.js/animo.js' %}"></script>
   <!-- SLIMSCROLL-->
   <script src="{% static 'theme/vendor/slimScroll/jquery.slimscroll.min.js' %}"></script>
   <!-- SCREENFULL-->
   <script src="{% static 'theme/vendor/screenfull/dist/screenfull.js' %}"></script>
   
   <!-- LOCALIZE-->
   <!-- <script src="{% static 'theme/vendor/jquery-localize-i18n/dist/jquery.localize.js' %}"></script> -->
	
	<!-- =============== APP SCRIPTS ===============-->
	{% render_block 'js' %}
   
	<script src="{% static 'theme/js/app.js' %}"></script>
	
	<script type="text/javascript">
	if (window.navigator.standalone) {
	    var a=document.getElementsByTagName("a");
		for(var i=0;i<a.length;i++)
		{
		    a[i].onclick=function()
		    {
		        window.location=this.getAttribute("href");
		        return false
		    }
		}
	}
	</script>
</body>
</html>

admin/templates/menu-old.html
<div data-type="horizontal" data-role="controlgroup" class="ui-btn-left">
	<a data-role="button" href="{% url 'clients:overview' %}" {% if active_item == 'clients' %}class="ui-btn-active"{% endif %}>Clients</a>
	<a data-role="button" href="{% url 'stock:overview' %}" {% if active_item == 'stock' %}class="ui-btn-active"{% endif %}>Stock</a>
</div>
	
<div data-type="horizontal" data-role="controlgroup" class="ui-btn-right">
	<a data-role="button" href="{% url 'accounts:settings' %}" {% if active_item == 'account' %}class="ui-btn-active"{% endif %}>Account</a>
</div>

admin/templates/menu.html
<div data-type="horizontal" data-role="controlgroup" class="ui-btn-left">
	<a data-role="button" href="{% url 'clients:overview' %}" {% if active_item == 'clients' %}class="ui-btn-active"{% endif %}>Clients</a>
	<a data-role="button" href="{% url 'stock:overview' %}" {% if active_item == 'stock' %}class="ui-btn-active"{% endif %}>Stock</a>
</div>
	
<div data-type="horizontal" data-role="controlgroup" class="ui-btn-right">
	<a data-role="button" href="{% url 'accounts:settings' %}" {% if active_item == 'account' %}class="ui-btn-active"{% endif %}>Account</a>
</div>

admin/templates/navigation.html
{% load staticfiles %}

<nav role="navigation" class="navbar topnavbar">
    <!-- START navbar header-->
    <div class="navbar-header">
       <a href="#/" class="navbar-brand">
          <div class="brand-logo">
             <img src="{% static 'images/sh-white.png' %}" style="height: 38px; margin-left: 5px;" alt="App Logo" class="img-responsive">
          </div>
          <div class="brand-logo-collapsed">
             <img src="{% static 'images/sh-white.png' %}" alt="App Logo" class="img-responsive">
          </div>
       </a>
    </div>
    <!-- END navbar header-->
    <!-- START Nav wrapper-->
    <div class="nav-wrapper">
       <!-- START Left navbar-->
       <ul class="nav navbar-nav">
          <li>
             <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
             <a href="#" data-toggle-state="aside-collapsed" class="hidden-xs">
                <em class="fa fa-navicon"></em>
             </a>
             <!-- Button to show/hide the sidebar on mobile. Visible on mobile only.-->
             <a href="#" data-toggle-state="aside-toggled" data-no-persist="true" class="visible-xs sidebar-toggle">
                <em class="fa fa-navicon"></em>
             </a>
          </li>
       </ul>
       <!-- END Left navbar-->
       <!-- START Right Navbar-->
       <ul class="nav navbar-nav navbar-right">
          <!-- Search icon-->
          <li>
             <a href="#" data-search-open="">
                <em class="icon-magnifier"></em>
             </a>
          </li>
          <!-- Fullscreen (only desktops)-->
          <li class="visible-lg">
             <a href="#" data-toggle-fullscreen="">
                <em class="fa fa-expand"></em>
             </a>
          </li>
          <!-- START Alert menu-->
          <li class="dropdown dropdown-list">
             <a href="#" data-toggle="dropdown">
                <em class="icon-bell"></em>
                <div class="label label-danger">11</div>
             </a>
             <!-- START Dropdown menu-->
             <ul class="dropdown-menu animated flipInX">
                <li>
                   <!-- START list group-->
                   <div class="list-group">
                      <!-- list item-->
                      <a href="#" class="list-group-item">
                         <div class="media-box">
                            <div class="pull-left">
                               <em class="fa fa-twitter fa-2x text-info"></em>
                            </div>
                            <div class="media-box-body clearfix">
                               <p class="m0">New followers</p>
                               <p class="m0 text-muted">
                                  <small>1 new follower</small>
                               </p>
                            </div>
                         </div>
                      </a>
                      <!-- list item-->
                      <a href="#" class="list-group-item">
                         <div class="media-box">
                            <div class="pull-left">
                               <em class="fa fa-envelope fa-2x text-warning"></em>
                            </div>
                            <div class="media-box-body clearfix">
                               <p class="m0">New e-mails</p>
                               <p class="m0 text-muted">
                                  <small>You have 10 new emails</small>
                               </p>
                            </div>
                         </div>
                      </a>
                      <!-- list item-->
                      <a href="#" class="list-group-item">
                         <div class="media-box">
                            <div class="pull-left">
                               <em class="fa fa-tasks fa-2x text-success"></em>
                            </div>
                            <div class="media-box-body clearfix">
                               <p class="m0">Pending Tasks</p>
                               <p class="m0 text-muted">
                                  <small>11 pending task</small>
                               </p>
                            </div>
                         </div>
                      </a>
                      <!-- last list item -->
                      <a href="#" class="list-group-item">
                         <small>More notifications</small>
                         <span class="label label-danger pull-right">14</span>
                      </a>
                   </div>
                   <!-- END list group-->
                </li>
             </ul>
             <!-- END Dropdown menu-->
          </li>
          <!-- END Alert menu-->
          <!-- START Offsidebar button-->
          <li>
             <a href="#" data-toggle-state="offsidebar-open" data-no-persist="true">
                <em class="icon-notebook"></em>
             </a>
          </li>
          <!-- END Offsidebar menu-->
          
          <li>
             <a href="{% url 'accounts:logout' %}" data-toggle-state="offsidebar-open" data-no-persist="true">
                <em class="icon-logout"></em>
             </a>
          </li> 
       </ul>
       <!-- END Right Navbar-->
    </div>
    <!-- END Nav wrapper-->
    <!-- START Search form-->
    <form role="search" action="search.html" class="navbar-form">
       <div class="form-group has-feedback">
          <input type="text" placeholder="Type and hit enter ..." class="form-control">
          <div data-search-dismiss="" class="fa fa-times form-control-feedback"></div>
       </div>
       <button type="submit" class="hidden btn btn-default">Submit</button>
    </form>
    <!-- END Search form-->
 </nav>

admin/templates/sidebar.html
<ul class="nav">
	  <!-- START user info-->
	  <li class="has-user-block">
	     <div id="user-block">
	        <div class="item user-block">
	           <!-- User picture-->
	           <div class="user-block-picture">
	              <div class="user-block-status">
	                 <div class="img-thumbnail img-circle" style="height: 60px; width: 60px; text-align: center; font-size: 23pt; padding-top: 4px;">
					 	<span class="fa fa-user"></span>
	                 </div>
	                 <div class="circle circle-success circle-lg"></div>
	              </div>
	           </div>
	           <!-- Name and Job-->
	           <div class="user-block-info">
	              <span class="user-block-name">Hello, {{ request.user.first_name }}</span>
	              <span class="user-block-role">Last login:<br />{{ request.user.last_login|date:"l jS F" }}</span>
	           </div>
	        </div>
	     </div>
	  </li>
	  <!-- END user info-->
	  <!-- Iterates over all sidebar items-->
	  <li class="nav-heading ">
	     <span data-localize="sidebar.heading.HEADER">Administration</span>
	  </li>
	  
	  <li class="{% if active_item == 'clients' %}active{% endif %}">
	     <a href="{% url 'clients:overview' %}" title="Clients">
	        <div class="pull-right label label-success">?</div>
	        <em class="icon-users"></em>
	        <span>Clients</span>
	     </a>
	  </li>
	  
	  <li class="{% if active_item == 'statistics' %}active{% endif %}">
	     <a href="#statistics" title="Statistics" data-toggle="collapse">
	        <div class="pull-right label label-info">3</div>
	        <em class="icon-speedometer"></em>
	        <span>Statistics</span>
	     </a>
	     <ul id="statistics" class="nav sidebar-subnav collapse">
	        <li class="sidebar-subnav-header">Statistics</li>
	        <li class="{% if active_subitem == 'facebook' %}active{% endif %}">
	           <a href="{% url 'statistics:facebook' %}" title="Facebook statistics">
	              <span>Facebook statistics</span>
	           </a>
	        </li>
	        <li class="{% if active_subitem == 'usage' %}active{% endif %}">
	           <a href="dashboard_v2.html" title="Usage statistics">
	              <span>Usage statistics</span>
	           </a>
	        </li>
	        <li class="{% if active_subitem == 'technical' %}active{% endif %}">
	           <a href="dashboard_v3.html" title="Technical statistics">
	              <span>Technical statistics</span>
	           </a>
	        </li>
	     </ul>
	  </li>
</ul>